services:
  - type: web
    name: booking-app
    env: python
    rootDirectory: "BACKEND/Booking_Backend"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Booking_Backend.wsgi:application"
    plan: free
    postdeploy: "python manage.py migrate && python manage.py collectstatic --noinput || true"
